config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'entries/new', to: 'entries#new', as: 'new_entries'
  post 'entries', to: 'entries#create'
  get 'entries/:id/edit', to: 'entries#edit', as: 'edit_entries'
  patch 'entries/:id', to: 'entries#update', as: 'entry'
  delete 'entries/:id', to: 'entries#destroy', as: 'delete_entries'
  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    before_action :set_entries, only: [:edit, :update, :delete]

    def index
        @entries_open = Entry.where(status: 'en curso')
        @entries_close = Entry.where(status: 'cerrada')
    end

    def new
        @entry = Entry.new
    end 

    def create
        @entry = Entry.new(entry_params)

        if @entry.save
            redirect_to root_path, notice: 'Entrada Guardada owo'
        else
            redirect_to new_entries_path, alert: 'Entrada no Guardada :('
        end
    end

    def edit
    end

    def update
        @entry.update(entry_params)
        if @entry.save
            redirect_to root_path, notice: 'Entrada Guardada owo'
        else
            redirect_to new_entry_path, alert: 'Entrada no Guardada :('
        end
    end
    private
    
    def entry_params
        params.require(:entry).permit(:title, :content, :status)
    end

    def set_entries
        @entry = Entry.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |f| %>
    <div class="row">
    <div class="row">
        <div class="column"> <%= f.label :titulo %></div>
        <div class="column"> <%= f.text_field :title %></div>
    </div>

    <div class="row">
        <div class="column"><%= f.label :contenido %></div>
        <div class="column"><%= f.text_area :content %>
    </div>
   
    </div>
    <div class="row">
        <div class="column"><%= f.label :status %></div>
        <div class="column"><%= f.select :status, options_for_select(['en curso', 'cerrada'])%></div>
    </div>
    </div>
    <br>
    <%= f.submit 'Guardar' %>

<% end %>
<br>

app/views/entries/edit.html.erb
<div>
    <h2>Editar Entrada</h2>
    <div>
        <%= render 'form', entry: @entry %>
    </div>

    <%= link_to 'volver', root_path %>
</div>

app/views/entries/index.html copy.erb
<div class="frame">
<h1> Todas las entradas </h1>

<div>
<h2>Entradas en curso </h2>
    <table class="tabla-post">
        <thead class="tabla-post"> 
            <th class="tabla-post" style="width: 180px">Fecha creacion</th>
            <th class="tabla-post" style="width: 200px">Titulo</th>
            <th class="tabla-post" style="width: 300px">Contenido</th>
            <th class="tabla-post" style="width: 100px">Estado</th>
            <th class="tabla-post">Acciones</th>
        </thead class="tabla-post">
        <% @entries_open.each do |entry| %>
            <tbody class="tabla-post">
                <td><%= entry.created_at %></td>
                <td><%= entry.title %></td>
                <td><%= entry.content %></td>
                <td><%= entry.status %></td>
                <td><%= link_to 'editar', edit_entries_path(entry) %> |
                <%= link_to 'eliminar', delete_entries_path(entry), method: :delete, data: {confirm: 'estas seguro?'} %></td>
            </tbody>
        <% end %>
    
    </table>
</div>

<div>
<h2>Entradas cerradas </h2>
    <table class="tabla-post">
        <thead class="tabla-post"> 
            <th class="tabla-post" style="width: 180px">Fecha creacion</th>
            <th class="tabla-post" style="width: 200px">Titulo</th>
            <th class="tabla-post" style="width: 300px">Contenido</th>
            <th class="tabla-post" style="width: 100px">Estado</th>
            <th class="tabla-post">Acciones</th>

        </thead class="tabla-post">
        <% @entries_close.each do |entry| %>
            <tbody class="tabla-post">
                <td><%= entry.created_at %></td>
                <td><%= entry.title %></td>
                <td><%= entry.content %></td>
                <td><%= entry.status %></td>
                <td><%= link_to 'editar', edit_entries_path(entry) %> |
                <%= link_to 'eliminar', delete_entries_path(entry), method: :delete, data: {confirm: 'estas seguro?'} %></td>
            </tbody>
        <% end %>
    
    </table>
</div>

</div>



<%= link_to 'Nueva Entrada', new_entries_path %>

app/views/entries/index.html.erb
<div class="frame">
<h1> Todas las entradas </h1>

<div>
<h2>Entradas en curso </h2>





    <table class="tabla-post">
        <thead class="tabla-post"> 
            <th class="tabla-post" style="width: 180px">Fecha creacion</th>
            <th class="tabla-post" style="width: 200px">Titulo</th>
            <th class="tabla-post" style="width: 300px">Contenido</th>
            <th class="tabla-post" style="width: 100px">Estado</th>
            <th class="tabla-post">Acciones</th>
        </thead class="tabla-post">
        <% @entries_open.each do |entry| %>
        <div class="card">
             <div class="card-body"> 
            <tbody class="tabla-post">
                <td><%= entry.created_at %></td>
                <td><%= entry.title %></td>
                <td><%= entry.content %></td>
                <td><%= entry.status %></td>
                <td><%= link_to 'editar', edit_entries_path(entry) %> |
                <%= link_to 'eliminar', delete_entries_path(entry), method: :delete, data: {confirm: 'estas seguro?'} %></td>
            </tbody>
        <% end %>
        </div>
        </div>
    
    </table>
</div>

<div>
<h2>Entradas cerradas </h2>
    <table class="tabla-post">
        <thead class="tabla-post"> 
            <th class="tabla-post" style="width: 180px">Fecha creacion</th>
            <th class="tabla-post" style="width: 200px">Titulo</th>
            <th class="tabla-post" style="width: 300px">Contenido</th>
            <th class="tabla-post" style="width: 100px">Estado</th>
            <th class="tabla-post">Acciones</th>

        </thead class="tabla-post">
        <% @entries_close.each do |entry| %>
            <tbody class="tabla-post">
                <td><%= entry.created_at %></td>
                <td><%= entry.title %></td>
                <td><%= entry.content %></td>
                <td><%= entry.status %></td>
                <td><%= link_to 'editar', edit_entries_path(entry) %> |
                <%= link_to 'eliminar', delete_entries_path(entry), method: :delete, data: {confirm: 'estas seguro?'} %></td>
            </tbody>
        <% end %>
    
    </table>
</div>

</div>



<%= link_to 'Nueva Entrada', new_entries_path %>

app/views/entries/new.html.erb
<div>
    <h2>Nueva Entrada</h2>
    <div>
        <%= render 'form', entry: @entry %>
    </div>

    <%= link_to 'volver', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>